/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backup;

/**
 *
 * @author Nitish Kumar
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setTitle("About Us | Knect");
        setPreferredSize(new java.awt.Dimension(669, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(669, 400));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("About Us");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 664, 51);

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Knect Online Secure Backup System focuses on creating secure backup system.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 70, 630, 40);

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Our main aim is to secure the data from accidental damages and various security");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 100, 660, 40);

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("threats. It uses SFTP channel to transfer files and AES encryption algorithms");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 130, 660, 40);

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("to safeguard the confidentiality of the user's data. We had used concept of salt ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 160, 660, 40);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("pruning to safeguard the passwords of the user. ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 190, 550, 40);

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText(" This project is made on 2nd Semester in MTech(IS). MNIT Allahabad, Prayagraj :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 240, 660, 40);

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("      BY  Nitish Kumar (2018IS09), Harshit Kumar(2018IS02), Ashutosh Jha (2018CS16)");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(-20, 270, 685, 40);

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(250, 310, 100, 30);

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("@ All Content Reserved  By | Knect Data Storage");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 330, 660, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 670, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
