package backup;

import static backup.SearchResult.table;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitish Kumar
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        phome.setBackground(new Color(0,102,255,50));

        blockh.setBackground(new Color(0,102,255,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        home1 = new javax.swing.JLabel();
        lprofile = new javax.swing.JLabel();
        sserver = new javax.swing.JLabel();
        lfile = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        fb = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        phome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        blockt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        blockh = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        size = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin DashBoard");
        setPreferredSize(new java.awt.Dimension(841, 477));
        setResizable(false);
        setSize(new java.awt.Dimension(841, 477));
        getContentPane().setLayout(null);

        home1.setBackground(new java.awt.Color(0, 102, 255));
        home1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        home1.setForeground(new java.awt.Color(0, 0, 255));
        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/home.png"))); // NOI18N
        home1.setText("Home");
        home1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        home1.setOpaque(true);
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
        });
        getContentPane().add(home1);
        home1.setBounds(20, 100, 180, 40);

        lprofile.setBackground(new java.awt.Color(0, 102, 255));
        lprofile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lprofile.setForeground(new java.awt.Color(0, 0, 255));
        lprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/list.png"))); // NOI18N
        lprofile.setText("List Profiles");
        lprofile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        lprofile.setOpaque(true);
        lprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lprofileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lprofileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lprofileMouseExited(evt);
            }
        });
        getContentPane().add(lprofile);
        lprofile.setBounds(20, 140, 180, 40);

        sserver.setBackground(new java.awt.Color(0, 102, 255));
        sserver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        sserver.setForeground(new java.awt.Color(0, 0, 255));
        sserver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/servers.png"))); // NOI18N
        sserver.setText("Set Server");
        sserver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        sserver.setOpaque(true);
        sserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sserverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sserverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sserverMouseExited(evt);
            }
        });
        getContentPane().add(sserver);
        sserver.setBounds(20, 180, 180, 40);

        lfile.setBackground(new java.awt.Color(0, 102, 255));
        lfile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lfile.setForeground(new java.awt.Color(0, 0, 255));
        lfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/log.png"))); // NOI18N
        lfile.setText("Log Files");
        lfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        lfile.setOpaque(true);
        lfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lfileMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lfileMouseReleased(evt);
            }
        });
        lfile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lfileKeyPressed(evt);
            }
        });
        getContentPane().add(lfile);
        lfile.setBounds(20, 220, 180, 40);

        logout1.setBackground(new java.awt.Color(0, 102, 255));
        logout1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        logout1.setForeground(new java.awt.Color(0, 0, 255));
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logout-1-128.png"))); // NOI18N
        logout1.setText("Log Out");
        logout1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        logout1.setOpaque(true);
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logout1MouseReleased(evt);
            }
        });
        logout1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logout1KeyPressed(evt);
            }
        });
        getContentPane().add(logout1);
        logout1.setBounds(20, 340, 180, 40);

        fb.setBackground(new java.awt.Color(0, 102, 255));
        fb.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        fb.setForeground(new java.awt.Color(0, 0, 255));
        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/feedback.png"))); // NOI18N
        fb.setText("FeedBacks");
        fb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        fb.setOpaque(true);
        fb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fbMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fbMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbMouseClicked(evt);
            }
        });
        fb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fbKeyPressed(evt);
            }
        });
        getContentPane().add(fb);
        fb.setBounds(20, 300, 180, 40);

        ss.setBackground(new java.awt.Color(0, 102, 255));
        ss.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        ss.setForeground(new java.awt.Color(0, 0, 255));
        ss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/server status.png"))); // NOI18N
        ss.setText("Server Status");
        ss.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        ss.setOpaque(true);
        ss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ssMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ssMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ssMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssMouseClicked(evt);
            }
        });
        ss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ssKeyPressed(evt);
            }
        });
        getContentPane().add(ss);
        ss.setBounds(20, 260, 180, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 30, 90, 50);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(null);

        header.setBackground(new java.awt.Color(0, 102, 204));
        header.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        header.setForeground(new java.awt.Color(102, 0, 51));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Admin Control Pannel");
        jPanel1.add(header);
        header.setBounds(180, 10, 550, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 790, 80);

        phome.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Enter User ProfileId:");
        phome.add(jLabel3);
        jLabel3.setBounds(30, 130, 250, 60);

        blockt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        blockt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blocktActionPerformed(evt);
            }
        });
        phome.add(blockt);
        blockt.setBounds(280, 130, 290, 60);

        jButton1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton1.setText("UnBlock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        phome.add(jButton1);
        jButton1.setBounds(430, 200, 140, 50);

        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setText("Block");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        phome.add(jButton2);
        jButton2.setBounds(280, 200, 140, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("User Profile Block");

        javax.swing.GroupLayout blockhLayout = new javax.swing.GroupLayout(blockh);
        blockh.setLayout(blockhLayout);
        blockhLayout.setHorizontalGroup(
            blockhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blockhLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        blockhLayout.setVerticalGroup(
            blockhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blockhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        phome.add(blockh);
        blockh.setBounds(100, 10, 390, 102);

        size.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        size.setText("Increase Allocated Size");
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });
        phome.add(size);
        size.setBounds(150, 280, 280, 50);

        getContentPane().add(phome);
        phome.setBounds(210, 100, 600, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/admin.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(886, 477));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 477);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFrame frame1;
public void Listprofile()
{
String[] columnNames = {"Sr No","Name", "Email", "Status", "Allocate Size","Size Used","Mobile","User Id"};
frame1 = new JFrame("All User Profile");
frame1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
frame1.setLayout(new BorderLayout());
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(columnNames);
table = new JTable();
table.setModel(model); 
table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
int Sr_no = 0;


try
{ 
Connection con=ConnectDB.connect();
String sql = "select * from regis_app";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
while(rs.next())
{
Sr_no = rs.getInt("Sr_no");


model.addRow(new Object[]{Sr_no,rs.getString("name") ,rs.getString("email") ,rs.getString("status"),rs.getLong("allocate_size"),rs.getLong("size_used"),rs.getLong("Mobile"),rs.getString("UserID") });
i++; 
}
if(i <1)
{
JOptionPane.showMessageDialog(null, "No Record Found","Error",JOptionPane.ERROR_MESSAGE);
return ;
}
if(i ==1)
{
System.out.println(i+" Record Found");
}
else
{
System.out.println(i+" Records Found");
}
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
JOptionPane.ERROR_MESSAGE);
}
frame1.add(scroll);
frame1.setVisible(true);
frame1.setSize(700,300);

}
    
    

public void feedbk()
{
String[] columnNames = {"Sr No","Name", "Email", "User ID", " Message"};
frame1 = new JFrame("User Feedbacks");
frame1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
frame1.setLayout(new BorderLayout());
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(columnNames);
table = new JTable();
table.setModel(model); 
table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
int Sr_no = 0;


try
{ 
Connection con=ConnectDB.connect();
String sql = "select * from feedback";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
while(rs.next())
{
Sr_no = rs.getInt("Sr_no");


model.addRow(new Object[]{Sr_no,rs.getString("Name") ,rs.getString("Email") ,rs.getString("Userid"),rs.getString("Message") });
i++; 
}
if(i <1)
{
JOptionPane.showMessageDialog(null, "No Record Found","Error",JOptionPane.ERROR_MESSAGE);
return ;
}
if(i ==1)
{
System.out.println(i+" Record Found");
}
else
{
System.out.println(i+" Records Found");
}
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
JOptionPane.ERROR_MESSAGE);
}
frame1.add(scroll);
frame1.setVisible(true);
frame1.setSize(700,300);

}



































    
    
    
    
    
    
    
    private void lprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lprofileMouseClicked

        Listprofile();
       
                 
        
        

    }//GEN-LAST:event_lprofileMouseClicked

    private void lprofileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lprofileMouseEntered
        lprofile.setBackground(new Color(0,0,255));
        lprofile.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lprofileMouseEntered

    private void lprofileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lprofileMouseExited
        lprofile.setBackground(new Color(0,102,255));
        lprofile.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lprofileMouseExited

    private void sserverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sserverMouseEntered
        // TODO add your handling code here:
        sserver.setBackground(new Color(0,0,255));
        sserver.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_sserverMouseEntered

    private void sserverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sserverMouseExited
        // TODO add your handling code here:
        sserver.setBackground(new Color(0,102,255));
        sserver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_sserverMouseExited

    private void lfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfileMouseEntered
        // TODO add your handling code here:
        lfile.setBackground(new Color(0,0,255));
        lfile.setForeground(new Color(255,255,255));

    }//GEN-LAST:event_lfileMouseEntered

    private void lfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfileMouseExited
        // TODO add your handling code here:
        lfile.setBackground(new Color(0,102,255));
        lfile.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lfileMouseExited

    private void lfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfileMousePressed

    }//GEN-LAST:event_lfileMousePressed

    private void lfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfileMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lfileMouseReleased

    private void lfileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lfileKeyPressed

    }//GEN-LAST:event_lfileKeyPressed

    private void logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseEntered
        // TODO add your handling code here:
         logout1.setBackground(new Color(0,0,255));
        logout1.setForeground(new Color(255,255,255));
        
        
    }//GEN-LAST:event_logout1MouseEntered

    private void logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseExited
        // TODO add your handling code here:
           logout1.setBackground(new Color(0,102,255));
        logout1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_logout1MouseExited

    private void logout1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MousePressed

    private void logout1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseReleased
        // TODO add your handling code here:
        setVisible(false);
        new Front().setVisible(true);
        
    }//GEN-LAST:event_logout1MouseReleased

    private void logout1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logout1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1KeyPressed

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        // TODO add your handling code here:
        home1.setBackground(new Color(0,102,255));
        home1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_home1MouseExited

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        home1.setBackground(new Color(0,0,255));
        home1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        phome.setVisible(true);
    }//GEN-LAST:event_home1MouseClicked
Connection Con;
    private void sserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sserverMouseClicked
        
         
        new tempserver().setVisible(true);
        
       
    }//GEN-LAST:event_sserverMouseClicked

    private void lfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfileMouseClicked
       SearchResult sr=new SearchResult();
       sr.showTableData();
        
        
    }//GEN-LAST:event_lfileMouseClicked

    private void fbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseClicked
feedbk();        
        
        
        
    }//GEN-LAST:event_fbMouseClicked

    private void fbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseEntered
        // TODO add your handling code here:
           fb.setBackground(new Color(0,0,255));
        fb.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_fbMouseEntered

    private void fbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseExited
        // TODO add your handling code here:
         fb.setBackground(new Color(0,102,255));
        fb.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_fbMouseExited

    private void fbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fbMousePressed

    private void fbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fbMouseReleased

    private void fbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fbKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fbKeyPressed

    private void ssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMouseClicked
       Serverstatus();
        
    }//GEN-LAST:event_ssMouseClicked

    private void ssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMouseEntered
        // TODO add your handling code here:
          ss.setBackground(new Color(0,0,255));
        ss.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ssMouseEntered

    private void ssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMouseExited
        // TODO add your handling code here:
        ss.setBackground(new Color(0,102,255));
        ss.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_ssMouseExited

    private void ssMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssMousePressed

    private void ssMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ssMouseReleased

    private void ssKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssKeyPressed

    private void blocktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blocktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blocktActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s=blockt.getText();
        Connection Con;
        try {
            Con = ConnectDB.connect();
            PreparedStatement  ps=Con.prepareStatement("UPDATE `regis_app` SET `status`='unblock' where`UserID`='"+s+"'");
            ps.execute();

            ps=Con.prepareStatement("insert into log(userid,action,time) value(?,?,?)");
            ps.setString(1, "Admin :Nah ");
            ps.setString(2, "UnBlocked User :"+s);
            LocalDateTime myDateObj = LocalDateTime.now();
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            ps.setString(3, myDateObj.format(myFormatObj));
            ps.execute();
            Con.close();
            blockt.setText("");
            JOptionPane.showMessageDialog(rootPane, s+ "User Unblock Successfully ");

        } catch (Exception ex) {

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void Serverstatus()
{
String[] columnNames = {"Sr No", "Server Name", "Server Ip", "Server Port","Status","Server User","Server Path"};
frame1 = new JFrame("Server Status");
frame1.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
frame1.setLayout(new BorderLayout());
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(columnNames);
table = new JTable();
table.setModel(model); 
table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
int Sr_no = 0;

try
{ 
Connection con=ConnectDB.connect();
String sql = "select * from servers";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
while(rs.next())
{
   
model.addRow(new Object[]{Sr_no,rs.getString("server_name") ,rs.getString("server_ip"),rs.getInt("server_port"),rs.getString("status"),rs.getString("server_user"),rs.getString("server_path") });
i++; 
}
if(i <1)
{
JOptionPane.showMessageDialog(null, "No Record Found","Error",JOptionPane.ERROR_MESSAGE);
return ;
}
if(i ==1)
{
System.out.println(i+" Record Found");
}
else
{
System.out.println(i+" Records Found");
}
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
JOptionPane.ERROR_MESSAGE);
}
frame1.add(scroll);
frame1.setVisible(true);
frame1.setSize(500,300);
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s=blockt.getText();

        try {
            Con = ConnectDB.connect();
            PreparedStatement  ps=Con.prepareStatement("UPDATE `regis_app` SET `status`='block' where`UserID`='"+s+"'");
            ps.execute();

            ps=Con.prepareStatement("insert into log(userid,action,time) value(?,?,?)");
            ps.setString(1, "Admin :Nah ");
            ps.setString(2, "Blocked User :"+s);
            LocalDateTime myDateObj = LocalDateTime.now();
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            ps.setString(3, myDateObj.format(myFormatObj));
            ps.execute();
            Con.close();
            blockt.setText("");
            JOptionPane.showMessageDialog(rootPane, s+ "user blocked Successfully ");

        } catch (Exception ex) {

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
       
       sizeincreased s=new sizeincreased();
       s.setLocation(210, 100);
       s.setVisible(true);
    }//GEN-LAST:event_sizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blockh;
    private javax.swing.JTextField blockt;
    private javax.swing.JLabel fb;
    private javax.swing.JLabel header;
    private javax.swing.JLabel home1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lfile;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel lprofile;
    private javax.swing.JPanel phome;
    private javax.swing.JButton size;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel sserver;
    // End of variables declaration//GEN-END:variables
}
