package backup;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitish Kumar
 */
public class home extends javax.swing.JFrame {

   //To change body of generated methods, choose Tools | Templates.
    

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        trans.setBackground(new Color(255,255,255,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trans = new javax.swing.JPanel();
        j2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        clik = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login | Knect");
        setBackground(new java.awt.Color(51, 0, 255));
        setForeground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(852, 490));
        setResizable(false);
        setSize(new java.awt.Dimension(852, 490));
        getContentPane().setLayout(null);

        trans.setLayout(null);

        j2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        j2.setForeground(new java.awt.Color(51, 51, 255));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        trans.add(j2);
        j2.setBounds(110, 170, 220, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHP\\p2\\images\\logo-dark.png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        trans.add(jLabel7);
        jLabel7.setBounds(160, 20, 80, 70);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Password :");
        trans.add(jLabel2);
        jLabel2.setBounds(10, 150, 90, 80);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Email ID :");
        trans.add(jLabel3);
        jLabel3.setBounds(10, 110, 80, 50);

        jButton1.setFont(new java.awt.Font("FrankRuehl", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        trans.add(jButton1);
        jButton1.setBounds(140, 230, 150, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("New User ? ");
        trans.add(jLabel4);
        jLabel4.setBounds(130, 270, 140, 40);

        clik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clik.setForeground(new java.awt.Color(255, 204, 0));
        clik.setText("Click Here");
        clik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clikMouseClicked(evt);
            }
        });
        trans.add(clik);
        clik.setBounds(230, 280, 70, 20);

        j1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        j1.setForeground(new java.awt.Color(51, 51, 255));
        trans.add(j1);
        j1.setBounds(110, 120, 220, 40);

        getContentPane().add(trans);
        trans.setBounds(400, 70, 360, 350);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 850, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setVisible(false);
        Front.main("5");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void clikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clikMouseClicked
        setVisible(false);
        new regis().setVisible(true);
    }//GEN-LAST:event_clikMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                if(j1.getText()!="" && j2.getText().contentEquals(""))
                {
                        
                    JOptionPane.showMessageDialog(rootPane, "Error: Please enter All Text Field ");
                            return ;
                }
        
        
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", j1.getText()))) 
                    { 
                           
                           
                            JOptionPane.showMessageDialog(rootPane, "Error: Please enter valid email address ");
                            return ;
                    }
        
        
        
        
        try {
            Connection Con= ConnectDB.connect();
            String q,w,e,r,t,y,u,b,log,ph,g;
            Long n;
            
             q=j1.getText();
             w=j2.getText();
             Statement st=Con.createStatement();
             ResultSet ty=st.executeQuery("SELECT * from regis_app");
             while(ty.next())
        {
            e=ty.getString("name");
            r=ty.getString("email");
         t=ty.getString("password");
         y=ty.getString("status");
         n=ty.getLong("Mobile");
         g=ty.getString("UserID");
         String access=w+g;
         MD5 md=new MD5();
         String w1;
         w1=md.getMd5(access);
        
         
         if((q.equals(r) )&& (w1.equals(t)))
            {
              
                
                setVisible(false);
           
               
                
                 PreparedStatement ps=Con.prepareStatement("insert into log(userid,action,time) value(?,?,?)");
                 ps.setString(1, g);
                 ps.setString(2,"Login");
                 LocalDateTime myDateObj = LocalDateTime.now();
                DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                ps.setString(3, myDateObj.format(myFormatObj));
                ps.execute();
                
                
                g=g+","+w;
                if(y.equals("block"))
                {
                     JOptionPane.showMessageDialog(rootPane, "Sorry Your Are blocked By admin. ");
                       new home().setVisible(true);
                       return;
                        
                }else{
                    if(y.equals("Admin"))
                    {
                        new backup.Admin().setVisible(true);
                    }else{
                    
                new backup.client(g).setVisible(true);
                System.out.println("hek8");
                    }
              return ;
                }
            
            }
        
            
        }
              
             JOptionPane.showMessageDialog(rootPane, "Error: Email or Password Incorrect ");
            
             
        
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String...args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clik;
    private javax.swing.JTextField j1;
    private javax.swing.JPasswordField j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel trans;
    // End of variables declaration//GEN-END:variables
}
