package Backup;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitish Kumar
 */
public class regis extends javax.swing.JFrame {

   //To change body of generated methods, choose Tools | Templates.
    

    /**
     * Creates new form home
     */
    public regis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        clck = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P2P");
        setBackground(new java.awt.Color(51, 0, 255));
        setForeground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(850, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Knect Registration ");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 80, 670, 74);

        l2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l2.setText("Email ID :");
        getContentPane().add(l2);
        l2.setBounds(250, 180, 80, 50);

        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setText("Name :");
        getContentPane().add(l1);
        l1.setBounds(270, 130, 90, 80);

        j1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        j1.setForeground(new java.awt.Color(51, 51, 255));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(340, 150, 310, 30);

        j2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 102, 255));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(340, 190, 310, 30);

        jButton1.setFont(new java.awt.Font("FrankRuehl", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 320, 150, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Already User ?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 350, 140, 50);

        clck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clck.setForeground(new java.awt.Color(255, 204, 0));
        clck.setText("Click Here");
        clck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clckMouseClicked(evt);
            }
        });
        getContentPane().add(clck);
        clck.setBounds(480, 370, 70, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\PHP\\p2\\images\\logo-dark.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, -10, 150, 120);

        j3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        j3.setForeground(new java.awt.Color(51, 51, 255));
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(340, 230, 310, 30);

        l3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l3.setText("Password :");
        getContentPane().add(l3);
        l3.setBounds(250, 200, 90, 80);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 230, 310, 30);

        j4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        j4.setForeground(new java.awt.Color(51, 51, 255));
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        getContentPane().add(j4);
        j4.setBounds(340, 270, 310, 30);

        l4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l4.setText("Mobile :");
        getContentPane().add(l4);
        l4.setBounds(260, 240, 80, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nitish Kumar\\Desktop\\1.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 852, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setVisible(false);
        Front.main("");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void clckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clckMouseClicked
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_clckMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            Connection Con= ConnectDB.connect();
            PreparedStatement ps=Con.prepareStatement("insert into regis_app(name,email,password,status,allocate_size,size_used,Mobile) value(?,?,?,?,?,?,?)");
             ps.setString(1, j1.getText());
              ps.setString(2, j2.getText());
               ps.setString(3, j3.getText());
                ps.setString(4, "unblock");
                 ps.setInt(5, Integer.parseInt("10000"));
                 ps.setInt(6, Integer.parseInt("10"));
                 ps.setInt(7, Integer.parseInt(j4.getText()));
                 
                 ps.execute();
                 setVisible(false);
                  new home().setVisible(true);
                // new successful().setVisible(true);
                
              
             
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(regis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(regis.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

                                  

 
    /**
     * @param args the command line arguments
     */
    public static void main(String...args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clck;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    // End of variables declaration//GEN-END:variables
}
